### ISSUE TITLE
Sensors from KNX not visible

### ISSUE THREAD

**Issue by rfcdejong** [lichr/zircon-ha-repository#3]
I have my temperature sensors from KNX integration. The monitor object shows a lot of entities and devices, but it doesn’t show my sensors. I created a template to hope it would become vissible then, but sadly it doesn’t show up either.
```

knx:
  switch:
    - name: "knx_verlichting_woonkamer"
      address: "1/1/1"
  sensor:
    - name: "knx_temp_woonkamer"
      type: temperature
      state_address: "1/3/0"
      state_class: measurement
      sync_state: every 15


template:
  - sensor:
      - name: "Woonkamer temperatuur"
        unit_of_measurement: "°C"
        state_class: measurement
        device_class: temperature
        state: "{{ states('sensor.knx_temp_woonkamer') }}"
```
